### PR TITLE
Optimized the fading out of the interface.

### PR DESCRIPTION
**Pull request by neauoire**

### CODE REVIEW

**Comment by neauoire** [comment]
screen shot 2018-10-11 at 2 44 14 pm

This is a bit opinionated, but I think the interface shouldn't hide the nice view.

**Comment by neauoire** [comment]
This also moved the rear camera into the camera toggle(world, top, etc)

**Comment by Rezmason** [comment]
Seems like the interface renders differently in different browsers.
Never done something like this before, but, I'll be pulling into a "workbench" branch and then into master once I get it to behave cross-browser.

Great stuff @neauoire ! 😊

image

**Comment by neauoire** [comment]
Oh cool! You've implemented `resolution` 👍

**Pull request merged**
